configure: look in /usr/include/tcl*.* for tcl.h 	problem reported by Michael Richter 	Fatal error if Tcl not found when --with-tcl given!

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1443,7 +1443,7 @@ fi
 if [ "$WITH_TCL" ]; then
     TCL_MAJOR_VERSION=0
     TCL_MINOR_VERSION=0
-    for TINCDIR in $INCDIR /usr/include /usr/local/include /usr/local/include/tcl*.*; do
+    for TINCDIR in $INCDIR /usr/include /usr/include/tcl*.* /usr/local/include /usr/local/include/tcl*.*; do
 	if [ -d "$TINCDIR" -a -f "$TINCDIR/tcl.h" ]; then
 	    MAJ=`grep 'TCL_MAJOR_VERSION' $TINCDIR/tcl.h | awk '{ print $3 }'`
 	    MIN=`grep 'TCL_MINOR_VERSION' $TINCDIR/tcl.h | awk '{ print $3 }'`
@@ -1477,6 +1477,7 @@ if [ "$WITH_TCL" ]; then
 		TCL_MAJOR_VERSION=$MAJ
 		TCL_MINOR_VERSION=$MIN
 		TCLINCDIR="$TINCDIR"
+		echo "found Tcl version $MAJ.$MIN" 1>&2
 
 		# Pick up Tk too, if needed (loads as package in 8.4+)
 		# makes a HUGE executable!!!
@@ -1522,6 +1523,9 @@ if [ "$WITH_TCL" ]; then
 	    echo 'ADD_CPPFLAGS([-I'$TCLINCDIR'])' >> $CONFIG_M4
 	fi
 	echo 'ADD_LDFLAGS([-l'$TCLLIB'])'	>> $CONFIG_M4
+    else
+	echo "Tcl library not found" 1>&2
+	exit 1
     fi
 fi
 
